application: phpcrontasks
version: 1
runtime: php
api_version: 1
threadsafe: true

handlers:

- url: /cron
  script: src/cronjobs.php
  
- url: /
  script: src/index.php
  
- url: /.*
  script: phpinfo.php


